export const fallbackSiteContent = {
  // 由 GET /api/v1/public/bootstrap 返回，结构对应 API 文档中的 BootstrapData schema
  site: {
    name: 'SACC',
    fullName: 'Science Association of Computer College',
    tagline: '探索科学之美，创造技术未来，成就卓越人生',
    logoUrl: '/image.png',
    domain: 'sacchome.ttdr.top.ttdr.top',
    publicIp: '123.56.221.147',
    email: 'hello@sacchome.ttdr.top.ttdr.top',
    footerStats: [],
    footerColumns: [
      {
        title: '官网导航',
        links: [
          { label: '首页', to: '/' },
          { label: '关于我们', to: '/about' },
          { label: '活动', to: '/activities' },
          { label: '项目', to: '/projects' },
        ],
      },
      {
        title: '内容中心',
        links: [
          { label: '文档库', to: '/docs' },
          { label: '成员动态', to: '/news' },
          { label: '项目展示', to: '/projects' },
          { label: '加入我们', to: '/join-us' },
        ],
      },
      {
        title: '快速上手',
        links: [
          { label: '项目概述', to: '/docs/project-overview' },
          { label: '技术方案', to: '/docs/tech-stack' },
          { label: '协作规范', to: '/docs/git-workflow' },
          { label: '新人指南', to: '/docs/onboarding' },
        ],
      },
    ],
    socialLinks: [
      { label: 'GitHub', href: 'https://github.com/' },
      { label: '邮箱', href: 'mailto:hello@sacchome.ttdr.top.ttdr.top' },
      { label: 'QQ 招新群', href: '/join-us' },
    ],
    cta: {
      title: '准备好加入我们了吗？',
      description: '和一群愿意把事情做成的人，一起把热爱变成作品、把成长做成履历。',
      primaryAction: { label: '加入我们', to: '/join-us' },
      secondaryAction: { label: '浏览文档库', to: '/docs' },
    },
  },
  navigation: [
    { label: '主页', to: '/' },
    { label: '关于我们', to: '/about' },
    { label: '文档库', to: '/docs' },
    { label: '成员动态', to: '/news' },
    { label: '项目', to: '/projects' },
  ],
  home: {
    eyebrow: '2026 SACC Official Site',
    title: '把热爱做成作品，把成长做成履历',
    subtitle:
      'SACC 不是“只看活动海报”的社团，而是一个围绕训练营、项目、竞赛和内容共创持续运转的技术共同体。',
    heroActions: [
      { label: '了解我们', to: '/about' },
      { label: '立即加入', to: '/join-us', tone: 'secondary' },
    ],
    stats: [
      { value: '500+', label: '累计成员' },
      { value: '50+', label: '年度活动' },
      { value: '20+', label: '合作企业' },
      { value: '100+', label: '获奖项目' },
    ],
    highlights: [
      {
        title: '技术训练营',
        description: '用完整学习路径覆盖前端、后端、AI、算法和设计协作，让新成员快速进入真实项目节奏。',
        link: '/activities',
      },
      {
        title: '创新项目孵化',
        description: '围绕校园服务、AI 应用和内容平台推进项目，让灵感最终变成可演示、可复盘的作品。',
        link: '/projects',
      },
      {
        title: '团队协同文化',
        description: '强调负责人机制、文档沉淀、版本管理和复盘，让协作能力和技术能力同步成长。',
        link: '/team/intro',
      },
      {
        title: '竞赛与荣誉',
        description: '通过专题集训、赛后复盘和经验传承，帮助成员在竞赛与科研中跑得更稳更远。',
        link: '/about',
      },
    ],
    testimonials: [
      '在 SACC 的两年，我真正完成了从“会写代码”到“能负责一项工作”的转变。',
      '这里最有价值的不是资源，而是遇到问题时总有人愿意一起把事情做成。',
      '项目制协作和竞赛训练让我第一次感受到，技术成长可以被认真设计。',
    ],
    partners: ['腾讯', '阿里巴巴', '字节跳动', '华为', '百度', '美团', '网易', '京东'],
    resources: [
      { value: '200+', label: '学习资料', description: '社内资料库沉淀了从基础到专题的结构化内容。' },
      { value: '50+', label: '视频回放', description: '训练营、分享会与项目复盘都可按主题回看。' },
      { value: '150+', label: '技术文章', description: '围绕工程实践、算法和 AI 应用持续沉淀。' },
      { value: '100+', label: '项目样例', description: '包含脚手架、设计稿、接口约定和部署示例。' },
    ],
  },
  about: {
    hero: {
      eyebrow: 'About SACC',
      title: '一个强调长期主义与交付结果的校园技术共同体',
      description:
        '我们不把官网当作单次展示页，而是把它看作项目工程、内容运营和社团品牌共同协作的窗口。',
    },
    missionCards: [
      {
        title: '使命',
        description: '让愿意投入的人找到方向、找到同伴、找到持续输出成果的舞台。',
      },
      {
        title: '愿景',
        description: '建设一个既能沉淀工程能力，也能承载校园影响力的技术社团品牌。',
      },
      {
        title: '方法',
        description: '训练营打基础，项目打协作，竞赛打强度，复盘打沉淀。',
      },
    ],
    capabilities: [
      '面向新成员的分层训练营与导师答疑机制',
      '真实项目组协作，覆盖设计、开发、测试、运营',
      '围绕竞赛、科研与实习目标的成长路线建议',
      '统一的文档沉淀、作品展示与内容发布体系',
    ],
    values: [
      { title: '专业', description: '不把“热爱”停留在口号，强调工程化、交付和复盘。' },
      { title: '协作', description: '明确负责人、节奏和边界，让每次共创都能闭环。' },
      { title: '创新', description: '鼓励成员从校园真实问题出发做新的产品和方案。' },
      { title: '成长', description: '用体系化路径帮助成员看到阶段性进步，而不是靠运气。' },
    ],
    timeline: [
      { year: '2023', title: '组织重构', description: '梳理了社团岗位分工与负责人机制，建立周会和复盘制度。' },
      { year: '2024', title: '项目制落地', description: '官网、活动报名系统和知识库等项目开始以产品形态推进。' },
      { year: '2025', title: '训练营成型', description: '围绕前端、后端、AI 和算法形成可复用的课程与作业体系。' },
      { year: '2026', title: '品牌升级', description: '启动官网重构、后台管理和部署规范，推动内容与工程一体化。' },
    ],
    honors: [
      '全国大学生程序设计竞赛金奖',
      '校级十佳社团品牌项目',
      '校园开放日优秀展示团队',
      '多家企业联合实践合作社团',
    ],
  },
  join: {
    eyebrow: 'Join SACC',
    title: '加入 SACC，与最能做事的人一起成长',
    subtitle:
      '你会在训练营、项目组和竞赛训练中建立技术能力、协作能力与表达能力，而不是只做旁观者。',
    groupNumber: '82391579',
    timeline: [
      { title: '报名入群', detail: '扫码或搜索群号 82391579，备注“姓名-学院-方向”。' },
      { title: '参加宣讲', detail: '了解培养路线、部门职责与项目节奏，确定个人方向。' },
      { title: '进入训练', detail: '根据方向加入学习小组，完成任务并进入面谈与分组。' },
    ],
    benefits: [
      '训练营 + 项目 + 竞赛的复合成长路线',
      '真实项目协作机会，可沉淀进简历与作品集',
      '学长学姐与负责人提供路线建议和作业反馈',
      '统一的内容库、代码规范和部署实践环境',
    ],
    tracks: [
      { title: '前端方向', description: 'React、工程化、设计还原、组件体系、部署交付。' },
      { title: '后端方向', description: 'Gin、Gorm、Redis、MySQL、接口设计与权限控制。' },
      { title: 'AI 方向', description: '检索增强、Agent 工作流、模型接入与应用落地。' },
      { title: '设计与运营', description: '品牌视觉、内容编排、活动包装和社群传播。' },
    ],
    requirements: [
      '愿意持续投入，而不是只打卡参加活动',
      '愿意写文档、做复盘、参与协作反馈',
      '愿意接受阶段性任务和团队责任',
    ],
  },
  activities: [
    {
      slug: 'programming-marathon-2025',
      title: '编程马拉松 2025',
      date: '2025-12-15',
      location: '创新实验中心',
      quota: 90,
      category: '竞赛活动',
      summary: '72 小时连续共创，完成从想法到原型的冲刺。',
      description:
        '编程马拉松 2025 面向全院同学开放，你将与队友在限定时间内完成从需求分析、原型设计到功能交付的完整闭环，体验真实项目冲刺节奏。',
      agenda: ['活动介绍与组队破冰', '需求拆解与原型设计', '导师巡回答疑与中期评审', '成果路演与现场评审'],
      outcomes: ['完成一份可演示原型', '体验高强度团队协作', '优秀项目获得展示与推荐机会'],
      linkLabel: '查看详情',
    },
    {
      slug: 'ai-tech-seminar',
      title: 'AI 技术研讨会',
      date: '2025-12-08',
      location: '信息楼报告厅',
      quota: 120,
      category: '研讨会',
      summary: '聚焦大模型、Agent 与校园应用场景分享。',
      description:
        '研讨会围绕大模型能力边界、RAG、Agent 编排与校园应用场景展开，结合社团内部项目和校友案例分享真实落地经验。',
      agenda: ['大模型与 Agent 趋势分享', '校园 AI 场景案例拆解', '成员项目经验交流', '开放问答与选题讨论'],
      outcomes: ['理解校园 AI 落地方向', '获得可执行的项目选题', '与 AI 方向成员建立交流'],
      linkLabel: '查看详情',
    },
    {
      slug: 'open-source-workshop',
      title: '开源工作坊',
      date: '2025-12-01',
      location: '实验楼 B105',
      quota: 60,
      category: '技术工作坊',
      summary: '从 Git 到协作流程，手把手完成第一次开源提交。',
      description:
        '工作坊通过真实仓库演示 issue、branch、PR、review 和合并流程，不只讲命令，更强调多人协作中的沟通边界与交付习惯。',
      agenda: ['Git 与分支协作基础', 'Issue 与 PR 提交流程', 'Code Review 与修改反馈', '合并发布与贡献记录'],
      outcomes: ['完成第一次开源提交', '理解多人协作流程', '掌握基础代码评审习惯'],
      linkLabel: '查看详情',
    },
  ],
  projects: [
    {
      slug: 'smart-knowledge-base',
      title: 'SACC 智能知识库',
      owner: 'AI 小组',
      summary: '为社团资料、活动手册和项目文档提供统一检索与问答入口。',
      progress: '85%',
      status: '在研',
      repoUrl: 'https://github.com/njupt-sacc/smart-knowledge-base',
      description:
        '项目围绕知识整理、检索增强和问答体验展开，目标是让成员能在一个入口里快速找到社团资料与历史沉淀。',
      architecture: ['内容采集层', '向量检索与缓存层', '问答服务层', '管理后台与权限层'],
      techStack: ['Gin', 'Gorm', 'Redis', 'MySQL', 'React', '向量检索'],
      challenges: [
        '文档结构不统一，历史资料质量参差不齐',
        '需要同时兼顾搜索速度、答案可信度和权限边界',
        '后台录入与审核流程必须支持多人协作',
      ],
      codeSample:
        "router.GET('/api/v1/public/bootstrap', controller.Bootstrap)\nrouter.POST('/api/v1/admin/auth/login', controller.Login)\ncache.Remember(ctx, 'site:bootstrap', 5*time.Minute, queryBootstrap)",
      roadmap: ['完成后台录入台', '接入知识分块与质量评估', '上线站内统一搜索入口'],
      awards: ['校级创新项目立项', '社团年度重点项目'],
      team: [
        { name: '林嘉禾', role: '前端负责人' },
        { name: '赵奕辰', role: '后端负责人' },
        { name: '顾安可', role: '内容策略' },
      ],
    },
    {
      slug: 'activity-registration-system',
      title: '校园活动报名系统',
      owner: 'Web 小组',
      summary: '统一报名、签到、统计与海报生成的校园活动服务平台。',
      progress: '60%',
      status: '开发中',
      repoUrl: 'https://github.com/njupt-sacc/activity-registration',
      description:
        '项目为社团和院系活动提供报名、签到、人数统计和基础运营支持，强调稳定性、权限控制和数据追踪。',
      architecture: ['前台报名页', '管理端审核页', '活动服务与报名服务', '统计与通知服务'],
      techStack: ['React', 'Gin', 'Redis', 'MySQL'],
      challenges: ['防止重复报名与刷接口', '活动状态切换的边界处理', '高峰期缓存与降级策略'],
      codeSample:
        "func (s *ActivityService) Reserve(ctx context.Context, req ReserveRequest) error {\n  return s.repo.WithTransaction(ctx, func(tx *gorm.DB) error {\n    return s.redisGuard.AcquireQuota(ctx, req.ActivityID, req.UserID)\n  })\n}",
      roadmap: ['补齐签到看板', '接入导出报表', '支持多组织共享模板'],
      awards: ['校级数字化建设实践案例'],
      team: [
        { name: '周亦晨', role: '项目 owner' },
        { name: '陈知远', role: '后端开发' },
        { name: '苏漫宁', role: '产品与运营' },
      ],
    },
    {
      slug: 'official-site-upgrade',
      title: '招新官网升级',
      owner: '前端组',
      summary: '围绕品牌、内容管理和部署规范完成官网从设计演示到真实工程的升级。',
      progress: '100%',
      status: '已交付',
      repoUrl: 'https://github.com/njupt-sacc/sacc-website',
      description:
        '项目重点不是“画出页面”，而是把官网前台、管理后台、内容模型、部署和安全边界整理成可持续维护的工程。',
      architecture: ['官网前台', '后台管理端', '内容服务', '部署与监控'],
      techStack: ['React', 'Gin', 'Gorm', 'Redis', 'MySQL', 'Nginx'],
      challenges: ['设计稿运行时依赖过重', '后台与官网数据割裂', '缺少部署和安全规范'],
      codeSample:
        "type PublicBootstrap struct {\n  Navigation []NavItem `json:\"navigation\"`\n  Home       HomePage  `json:\"home\"`\n  Site       SiteMeta  `json:\"site\"`\n}",
      roadmap: ['接入正式内容审核流', '支持图片与媒体资源管理', '补齐灰度发布与监控告警'],
      awards: ['社团年度品牌升级项目'],
      team: [
        { name: '林嘉禾', role: '前端负责人' },
        { name: '赵奕辰', role: '后端负责人' },
        { name: '顾安可', role: '品牌与内容' },
      ],
    },
  ],
  news: [
    {
      slug: 'server-components-notes',
      title: '把首屏交给 Server Components：官网性能优化实录',
      category: '工程实践',
      coverImage: '/images/blog-cover-performance.png',
      author: '林嘉禾',
      authorAvatar: '/uploads/avatars/linjiahe.png',
      role: '前端负责人',
      date: '2026-04-06',
      readMinutes: 8,
      tags: ['Next.js', '性能', 'React'],
      summary: '记录我们如何用 Server Components + 流式渲染把官网首屏 JS 压到接近为零，Lighthouse 冲到 96。',
      content: [
        '## 问题背景',
        '官网重构最想解决的是首屏体验。旧版把设计稿当运行时数据源，导致大量 JS 在客户端解析，首屏经常卡在白屏。',
        '## 优化方案',
        '这次我们把内容渲染尽量下沉到 Server Components，只有真正需要交互的部分才作为 Client Component 注水，配合 Suspense 做流式渲染。',
        '## 优化结果',
        '实测下来，首屏传输的 JS 体积下降了七成，Lighthouse Performance 从 71 提升到 96，首屏时间稳定在 1.2s 以内。',
        '## 一点经验',
        '先问“这段 UI 需要交互吗”，不需要就别让它进客户端。约束越早建立，后期越省心。',
      ].join('\n'),
    },
    {
      slug: 'route-scroll-restoration',
      title: '显式路由改造：告别运行时解析设计稿',
      category: '工程实践',
      coverImage: '/images/blog-cover-routing.png',
      author: '林嘉禾',
      authorAvatar: '/uploads/avatars/linjiahe.png',
      role: '前端负责人',
      date: '2026-04-04',
      readMinutes: 6,
      tags: ['React Router', '重构', '工程化'],
      summary: '把官网从“运行时读取设计稿驱动路由”改成稳定的显式路由，顺带理清了滚动恢复与页面结构。',
      content: [
        '## 为什么要改',
        '旧方案在运行时解析设计稿来决定路由和跳转，任何文案调整都可能让链接失效，维护起来非常脆弱。',
        '## 改造做法',
        '我们把每个页面都写成显式的 React 组件与路由，内容来自结构化数据模型，链接不再依赖文本匹配。',
        '## 附带收益',
        '路由清晰之后，滚动恢复、404 兜底和页面级布局都更好处理，新人也更容易看懂项目结构。',
      ].join('\n'),
    },
    {
      slug: 'rag-knowledge-base',
      title: '给社团知识库接上检索增强：一次 RAG 落地复盘',
      category: 'AI 应用',
      author: '沈知白',
      authorAvatar: '/uploads/avatars/shenzhibai.png',
      role: 'AI 方向负责人',
      date: '2026-04-02',
      readMinutes: 10,
      tags: ['RAG', 'Agent', '向量检索'],
      summary: '从文档切分、向量化到答案可信度评估，聊聊智能知识库项目里踩过的坑和最终方案。',
      content: [
        '## 难点在数据',
        '知识库最大的难点不是模型，而是数据。社团历史资料结构不统一，直接喂给模型只会得到一本正经的胡说八道。',
        '## 检索与作答',
        '我们先做了统一的文档分块策略，再用向量检索召回候选段落，最后让模型基于召回内容作答，并强制附带来源。',
        '## 控制幻觉',
        '为了控制“幻觉”，我们加了一层答案可信度评估：召回相似度过低时直接回复“暂无相关资料”，而不是硬编。',
        '## 下一步',
        '会把录入与审核流程搬进后台，让内容维护也能多人协作。',
      ].join('\n'),
    },
    {
      slug: 'gin-gorm-permission',
      title: 'Gin + Gorm 权限中间件的三个设计取舍',
      category: '后端',
      author: '赵奕辰',
      authorAvatar: '/uploads/avatars/zhaoyichen.png',
      role: '后端负责人',
      date: '2026-03-29',
      readMinutes: 7,
      tags: ['Gin', 'Gorm', '鉴权'],
      summary: '后台鉴权链路怎么设计才能既安全又好维护？分享我们在 RBAC、缓存和审计日志上的选择。',
      content: [
        '## 默认拒绝',
        '后台接口的第一原则是默认拒绝。我们用中间件统一拦截，未通过鉴权的请求根本进不到业务层。',
        '## 权限模型',
        '权限模型选了轻量 RBAC，角色到权限的映射放 Redis 缓存，变更时主动失效，避免每次都查库。',
        '## 审计日志',
        '所有写操作都会落一条审计日志，谁在什么时间改了什么一目了然，这在多人协作时特别重要。',
      ].join('\n'),
    },
    {
      slug: 'design-token-system',
      title: '从零搭一套 Design Token：让协作不再靠猜',
      category: '设计协作',
      author: '苏漫宁',
      authorAvatar: '/uploads/avatars/sumanning.png',
      role: '品牌视觉',
      date: '2026-03-24',
      readMinutes: 6,
      tags: ['Design Token', 'Tailwind', '组件'],
      summary: '色板、间距、圆角、阴影统一成变量后，前端还原设计稿的效率明显变高了。',
      content: [
        '## 问题',
        '以前设计和开发对不齐颜色是常态，一个橙色能有五个色值。这次我们把设计决策沉淀成 Design Token。',
        '## 落地方式',
        '所有 token 以 CSS 变量形式落地，Tailwind 直接引用，改一处全站生效，暗色模式也顺带解决了。',
        '## 结论',
        '设计规范不是给设计师看的 PDF，而是能被代码直接消费的变量表。',
      ].join('\n'),
    },
    {
      slug: 'trunk-based-practice',
      title: '小团队也能用好 Trunk-Based 开发',
      category: '协作复盘',
      author: '周亦晨',
      authorAvatar: '/uploads/avatars/zhouyichen.png',
      role: '主席',
      date: '2026-03-20',
      readMinutes: 5,
      tags: ['Git', 'CI/CD', '协作'],
      summary: '短分支 + PR Review + 自动预览，一套适合学生团队的协作流程是怎么跑起来的。',
      content: [
        '## 分支策略',
        '我们放弃了复杂的 Git Flow，改用 main 保护分支加短生命周期的 feature 分支。',
        '## PR 与预览',
        '每个 PR 都会触发 Vercel Preview，Review 时直接点链接看效果，比截图沟通高效太多。',
        '## 自动化保障',
        '规范落地的关键是自动化：Lint、类型检查、测试都在 CI 里跑，不合格就合不进来。',
      ].join('\n'),
    },
    {
      slug: 'first-open-source-pr',
      title: '我的第一次开源提交：从害怕到上瘾',
      category: '成长故事',
      author: '顾安可',
      authorAvatar: '/uploads/avatars/guanke.png',
      role: '运营策划',
      date: '2026-03-15',
      readMinutes: 4,
      tags: ['开源', '新人', '成长'],
      summary: '一个非科班同学，如何在开源工作坊里完成人生第一个被合并的 PR。',
      content: [
        '## 一开始的恐惧',
        '第一次看到满屏的 issue 和 PR，我是懵的，连 fork 和 clone 的区别都分不清。',
        '## 完成第一个 PR',
        '工作坊手把手带着走了一遍流程，我提交的文档修正 PR 被合并那一刻，成就感直接拉满。',
        '## 给新人的话',
        '别怕提问，也别怕提 PR，开源社区远比想象中友好。',
      ].join('\n'),
    },
  ],
  docs: [
    {
      slug: 'project-overview',
      title: '项目概述',
      category: '入门',
      order: 1,
      updatedAt: '2026-04-05',
      description: '了解南邮科协官网建设项目的背景、目标与整体范围。',
      content: [
        '# 项目概述',
        '南邮科协官网（SACC Website）V1.0 是技术部前端组在 Summer of Code 期间从零搭建的官方站点，覆盖需求分析、技术选型、架构设计、UI 开发到部署上线的全流程。',
        '## 项目背景',
        '科协目前尚无独立官方网站，对外宣传、活动发布、成果展示、招新报名均依赖零散的第三方平台，缺乏统一的品牌形象与信息集散入口。',
        '## 项目目标',
        '- 品牌建立：打造统一的科协视觉形象与线上门户。',
        '- 全端适配：完美兼容 PC / 平板 / 移动端。',
        '- 高性能：Lighthouse 评分不低于 90，首屏加载小于 2 秒。',
        '- 内容可维护：基于 MDX 文件驱动，内容即代码，无需数据库。',
        '- 组件化沉淀：积累一套可复用的 UI 组件。',
        '## 交付范围',
        '本期交付包括官网前台、内容管理后台原型、UI 组件库、设计规范文档以及面向新成员的上手指南。',
      ].join('\n'),
    },
    {
      slug: 'tech-stack',
      title: '技术方案',
      category: '入门',
      order: 2,
      updatedAt: '2026-04-03',
      description: '前端组的技术选型与项目结构约定。',
      content: [
        '# 技术方案',
        '我们围绕 React 生态构建现代化、高性能、低维护成本的站点。',
        '## 技术选型',
        '- 核心框架：React 19 + TypeScript，类型安全利于长期维护。',
        '- 元框架：Next.js 15 App Router，SSR/SSG/ISR 三合一。',
        '- 样式方案：Tailwind CSS 4，原子化 CSS 提升开发效率。',
        '- 组件体系：shadcn/ui + Radix Primitives，可访问性内置。',
        '- 内容层：MDX，文章与公告以文件形式存储于仓库。',
        '## 核心特性',
        '- Server Components 让首屏零 JS 传输。',
        '- 流式渲染搭配 Suspense 实现渐进式内容呈现。',
        '- ISR 让内容页面按需增量更新。',
        '- Dark Mode 基于 CSS 变量与 Tailwind 修饰符。',
        '## 项目结构',
        '源码采用 App Router 组织路由，组件划分为通用 UI、布局与页面区块三层，内容统一放在 content 目录下的 MDX 文件中。',
      ].join('\n'),
    },
    {
      slug: 'git-workflow',
      title: 'Git 协作规范',
      category: '规范',
      order: 3,
      updatedAt: '2026-03-30',
      description: '分支策略、提交规范与 PR 流程约定。',
      content: [
        '# Git 协作规范',
        '统一的协作规范能让多人开发保持节奏一致、历史清晰。',
        '## 分支策略',
        '采用 Trunk-Based 模式：main 为保护分支，功能开发使用短生命周期的 feature 分支。',
        '## 提交规范',
        '提交信息使用前缀区分类型：feat 新功能、fix 修复、docs 文档、chore 杂务、refactor 重构。',
        '## PR 流程',
        '- feature 分支开发完成后提交 PR。',
        '- 组长进行 Code Review。',
        '- 通过后 Squash Merge 合入。',
        '- 自动部署 Preview，验证后合入 main。',
        '## 环境约定',
        'main 自动部署生产环境，PR 分支自动部署预览地址，便于评审。',
      ].join('\n'),
    },
    {
      slug: 'onboarding',
      title: '新成员上手指南',
      category: '规范',
      order: 4,
      updatedAt: '2026-03-28',
      description: '从环境搭建到第一次贡献的完整流程。',
      content: [
        '# 新成员上手指南',
        '欢迎加入前端组，这份指南帮助你在第一周内完成环境搭建并提交首个 PR。',
        '## 环境搭建',
        '- 安装 Node.js 与 pnpm。',
        '- 克隆仓库并运行 pnpm install。',
        '- 使用 pnpm dev 启动本地开发服务。',
        '## 第一次贡献',
        '- 从 good first issue 里挑一个任务。',
        '- 基于 main 切出 feature 分支。',
        '- 完成开发并自测，提交 PR 等待 Review。',
        '## 学习路线',
        '建议先熟悉 React 与 TypeScript 基础，再逐步了解 Next.js 路由与 MDX 内容管线。遇到问题优先在群里提问，团队鼓励主动沟通。',
      ].join('\n'),
    },
    {
      slug: 'ui-components',
      title: 'UI 组件库说明',
      category: '组件',
      order: 5,
      updatedAt: '2026-04-01',
      description: '通用组件的定位、命名与使用约定。',
      content: [
        '# UI 组件库说明',
        '组件库沉淀在 src/components/ui 下，供科协后续活动页面直接复用。',
        '## 设计原则',
        '- 无头优先：交互与样式解耦，便于二次定制。',
        '- 可访问性内置：键盘导航与 ARIA 属性默认支持。',
        '- 零运行时膨胀：复制即拥有，不引入重型依赖。',
        '## 常用组件',
        '- Button：主按钮、次按钮与图标按钮三类变体。',
        '- Card：内容卡片，承载文档、动态与项目摘要。',
        '- Badge：状态标签，用于分类与进度标记。',
        '- Skeleton：加载骨架，配合流式渲染使用。',
        '## 使用约定',
        '优先复用现有组件，确需新增时先在组件库登记，保持命名与目录结构统一。',
      ].join('\n'),
    },
  ],
  team: {
    intro: {
      title: '团队不是按职位堆人，而是按目标协同',
      description:
        'SACC 采用负责人机制与项目制协作，每个方向都要对结果、节奏和文档沉淀负责，确保团队能稳定交付。',
    },
    leadership: [
      { name: '周亦晨', role: '主席', avatar: '/uploads/avatars/zhouyichen.png', focus: '统筹组织治理、合作拓展与年度项目规划。' },
      { name: '许沐安', role: '副主席', avatar: '/uploads/avatars/xumuan.png', focus: '负责训练营规划、招新节奏与部门协同。' },
      { name: '陈思远', role: '秘书长', avatar: '/uploads/avatars/chensiyuan.png', focus: '推进周会复盘、制度沉淀和组织节奏管理。' },
    ],
    technical: [
      { name: '林嘉禾', role: '前端负责人', avatar: '/uploads/avatars/linjiahe.png', focus: '官网、后台、组件体系和设计还原。' },
      { name: '赵奕辰', role: '后端负责人', avatar: '/uploads/avatars/zhaoyichen.png', focus: '接口设计、权限控制、缓存与部署。' },
      { name: '沈知白', role: 'AI 方向负责人', avatar: '/uploads/avatars/shenzhibai.png', focus: '知识库、Agent 和大模型应用工程化。' },
    ],
    nonTechnical: [
      { name: '顾安可', role: '运营策划', avatar: '/uploads/avatars/guanke.png', focus: '内容节奏、活动包装和社群沟通。' },
      { name: '苏漫宁', role: '品牌视觉', avatar: '/uploads/avatars/sumanning.png', focus: '官网视觉、活动物料与品牌规范。' },
      { name: '程彦宁', role: '外联合作', avatar: '/uploads/avatars/chengyanning.png', focus: '企业合作、讲座邀约与资源对接。' },
    ],
  },
  gallery: {
    albums: [
      {
        slug: 'spring-recruiting',
        title: '2026 春季招新宣讲',
        date: '2026-03-10',
        summary: '招新宣讲、展位互动与现场答疑的精选记录。',
        accent: 'warm',
      },
      {
        slug: 'project-demo-day',
        title: '项目路演日',
        date: '2026-03-05',
        summary: '项目组阶段性成果展示、答辩和现场交流照片。',
        accent: 'blue',
      },
      {
        slug: 'algorithm-camp',
        title: '算法训练营结营',
        date: '2026-02-28',
        summary: '训练营答辩、荣誉表彰与成员合影留存。',
        accent: 'sand',
      },
    ],
    archiveYears: [
      { year: '2026', count: 18 },
      { year: '2025', count: 22 },
      { year: '2024', count: 13 },
    ],
  },
  faq: [
    {
      question: '没有项目经验，可以加入吗？',
      answer: '可以。我们有面向不同基础的训练路径，关键是愿意持续投入、愿意接受任务和反馈。',
    },
    {
      question: '加入后一定要参加竞赛吗？',
      answer: '不一定。竞赛是路径之一，项目、内容共创、运营与设计协作同样重要。',
    },
    {
      question: '官网内容以后怎么维护？',
      answer: '本次重构会让官网逐步切换到后端内容接口和管理端驱动，而不是继续把设计稿当运行时数据源。',
    },
    {
      question: '可以同时参与多个方向吗？',
      answer: '可以，但建议先确定主方向，先保证主方向的交付，再逐步横向扩展。',
    },
  ],
}

export type SiteContent = typeof fallbackSiteContent
export type SiteNavigationItem = SiteContent['navigation'][number]
export type SiteFooterColumn = SiteContent['site']['footerColumns'][number]
export type SiteFooterLink = SiteFooterColumn['links'][number]
export type SiteStatistic = SiteContent['site']['footerStats'][number]
export type SiteAction = SiteContent['site']['cta']['primaryAction']
export type ActivityItem = SiteContent['activities'][number]
export type ProjectItem = SiteContent['projects'][number]
export type NewsItem = SiteContent['news'][number]
export type DocItem = SiteContent['docs'][number]
export type TeamCollection = SiteContent['team']
export type TeamMember = TeamCollection['leadership'][number]
