export const WEBSITE_ROUTES = [
  { path: '/', pageName: '首页' },
  { path: '/about', pageName: '关于我们' },
  { path: '/activities', pageName: '活动' },
  { path: '/activities/detail', pageName: '活动详情' },
  { path: '/activities/:activityId', pageName: '活动详情' },
  { path: '/join-us', pageName: '加入我们' },
  { path: '/projects', pageName: '项目' },
  { path: '/projects/detail', pageName: '项目详情' },
  { path: '/projects/:projectId', pageName: '项目详情' },
  { path: '/projects/team', pageName: '团队介绍' },
  { path: '/projects/:projectId/team', pageName: '团队介绍' },
  { path: '/tech/detail', pageName: '技术详情' },
  { path: '/team', pageName: '团队架构-主席团' },
  { path: '/team/intro', pageName: '团队介绍' },
  { path: '/team/leadership', pageName: '团队架构-主席团' },
  { path: '/team/non-technical', pageName: '团队架构-非技术部门' },
  { path: '/team/technical', pageName: '团队架构-技术部门' },
  { path: '/news', pageName: '动态' },
  { path: '/news/detail', pageName: '动态详情' },
  { path: '/news/:newsId', pageName: '动态详情' },
  { path: '/gallery', pageName: '相册' },
  { path: '/gallery/archive', pageName: '相册归档' },
  { path: '/faq', pageName: '常见问题' },
  { path: '/404', pageName: '404 页面' },
]
